import React, { useEffect, useState } from "react";
import { api } from "../api.js";
import VerificationStatusBadge from "./VerificationStatusBadge.jsx";
import BlockchainStatusBadge from "./BlockchainStatusBadge.jsx";

function fmtTime(ts) {
  return ts ? new Date(ts * 1000).toLocaleString() : "—";
}

function fmtHash(h) {
  return h ? `${h.slice(0, 16)}...${h.slice(-8)}` : "—";
}

function downloadJson(filename, data) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function openPrintableReport(report) {
  const w = window.open("", "_blank");
  if (!w) return;
  const rows = Object.entries({
    "Verification ID": report.verification_id,
    "REC ID": report.rec_id,
    "Generated At": fmtTime(report.generated_at),
    "Verifier Company": report.verifier_company || "—",
    "Verifier User": report.verifier_user || "—",
    "Verification Timestamp": fmtTime(report.verification_timestamp),
    "Result": report.result,
    "Blockchain Status": report.blockchain_status,
    "Hash Status": report.hash_status,
    "Lifecycle Status": report.lifecycle_status,
    "Risk Score": report.risk_score,
  }).map(([k, v]) => `<tr><th style="text-align:left;padding:6px 12px;color:#555">${k}</th><td style="padding:6px 12px">${v}</td></tr>`).join("");
  const reasons = (report.reasons || []).map((r) => `<li>${r}</li>`).join("") || "<li>None</li>";
  w.document.write(`
    <html><head><title>Verification Report ${report.verification_id}</title>
    <style>body{font-family:system-ui,sans-serif;padding:32px;color:#111}h1{font-size:20px}table{border-collapse:collapse;margin:16px 0}</style>
    </head><body>
    <h1>REC Guard -- Verification Report</h1>
    <table>${rows}</table>
    <h3>Reasons</h3><ul>${reasons}</ul>
    <p style="color:#888;font-size:12px">Generated by REC Guard's Verification Portal. This report reflects exactly what was decided at verification time and cannot be edited.</p>
    <script>window.onload = () => window.print();</script>
    </body></html>
  `);
  w.document.close();
}

export default function RecVerification({ resetEpoch = 0, initialRecId = "" }) {
  const [recId, setRecId] = useState(initialRecId);
  const [company, setCompany] = useState("");
  const [verifierUser, setVerifierUser] = useState("");
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [busy, setBusy] = useState(false);
  const [history, setHistory] = useState([]);
  const [auditLog, setAuditLog] = useState([]);

  useEffect(() => {
    if (resetEpoch > 0) {
      setResult(null);
      setHistory([]);
      setAuditLog([]);
    }
  }, [resetEpoch]);

  // Deep-linked from the Graph Fraud Detection page (click a REC ID there)
  // -- re-runs whenever a new initialRecId arrives, not just on first mount.
  useEffect(() => {
    if (initialRecId) {
      setRecId(initialRecId);
      runVerify(null, initialRecId);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialRecId]);

  async function runVerify(e, overrideRecId) {
    e?.preventDefault();
    const target = (overrideRecId ?? recId).trim();
    if (!target) return;
    setBusy(true);
    setError(null);
    setResult(null);
    try {
      const res = await api.verifyRecPortal(target, {
        verifier_company: company.trim() || undefined,
        verifier_user: verifierUser.trim() || undefined,
      });
      setResult(res);
      const [h, a] = await Promise.all([
        api.recVerificationHistory(target).catch(() => []),
        api.recAuditHistory(target).catch(() => []),
      ]);
      setHistory(h);
      setAuditLog(a);
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  }

  async function shareReport() {
    if (!result?.verification_id) return;
    try {
      const report = await api.verificationReport(result.verification_id);
      downloadJson(`${report.verification_id}.json`, report);
    } catch (err) {
      alert(`Could not generate report: ${err.message}`);
    }
  }

  async function printReport() {
    if (!result?.verification_id) return;
    try {
      const report = await api.verificationReport(result.verification_id);
      openPrintableReport(report);
    } catch (err) {
      alert(`Could not generate report: ${err.message}`);
    }
  }

  const rec = result?.rec;

  return (
    <div>
      <h1 className="text-2xl font-bold mb-1">Verify REC</h1>
      <p className="text-slate-400 text-sm mb-6">
        Independent tamper detection for a single REC -- for internal operators, another company, a buyer, or an
        auditor. Every check re-reads current data, recalculates its hash, and cross-checks the local blockchain,
        rather than trusting whatever SQLite currently says.
      </p>

      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 mb-6">
        <h3 className="text-xs uppercase tracking-wide text-slate-400 mb-4">External Company Verification</h3>
        <form onSubmit={runVerify} className="grid grid-cols-1 sm:grid-cols-4 gap-3 items-end">
          <label className="block text-xs text-slate-400 sm:col-span-2">
            REC ID
            <input
              value={recId}
              onChange={(e) => setRecId(e.target.value)}
              placeholder="e.g. REC-a1b2c3d4e5"
              className="mt-1 w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-sm font-mono"
            />
          </label>
          <label className="block text-xs text-slate-400">
            Company Name (optional)
            <input
              value={company}
              onChange={(e) => setCompany(e.target.value)}
              placeholder="Green Energy Trading Ltd."
              className="mt-1 w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-sm"
            />
          </label>
          <label className="block text-xs text-slate-400">
            Verifier Name (optional)
            <input
              value={verifierUser}
              onChange={(e) => setVerifierUser(e.target.value)}
              placeholder="Auditor 01"
              className="mt-1 w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-sm"
            />
          </label>
          <button
            disabled={busy || !recId.trim()}
            className="sm:col-span-4 bg-emerald-700 hover:bg-emerald-600 disabled:opacity-50 rounded-lg py-2.5 text-sm font-semibold"
          >
            {busy ? "Verifying..." : "Verify"}
          </button>
        </form>
        <p className="text-[11px] text-slate-600 mt-2">
          External verifiers can only read and check a REC -- verifying never edits the underlying record.
        </p>
      </div>

      {error && <div className="mb-6 text-sm bg-red-950/40 border border-red-900 text-red-400 rounded-lg px-4 py-3">{error}</div>}

      {result && (
        <div className="space-y-6">
          {/* headline */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
            <div className="flex items-center justify-between flex-wrap gap-3 mb-4">
              <div>
                <div className="text-xs text-slate-500 uppercase tracking-wide mb-1">REC Verification</div>
                <div className="text-xl font-mono font-bold">{result.rec_id}</div>
              </div>
              <VerificationStatusBadge result={result.result} size="large" />
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs">
              <div>
                <div className="text-slate-500 mb-1">Blockchain Verification</div>
                <BlockchainStatusBadge status={result.blockchain_status} />
              </div>
              <div>
                <div className="text-slate-500 mb-1">Data Integrity</div>
                <span className={`badge ${result.hash_status === "MATCHED" ? "bg-emerald-900/40 text-emerald-400" : "bg-red-900/40 text-red-400"}`}>
                  {result.hash_status}
                </span>
              </div>
              <div>
                <div className="text-slate-500 mb-1">Lifecycle</div>
                <span className={`badge ${result.lifecycle_status === "VALID" ? "bg-emerald-900/40 text-emerald-400" : "bg-red-900/40 text-red-400"}`}>
                  {result.lifecycle_status}
                </span>
              </div>
              <div>
                <div className="text-slate-500 mb-1">Fraud Risk</div>
                <span className="font-semibold">{result.final_risk_score}</span>
              </div>
            </div>
            {result.reasons?.length > 0 && (
              <div className="mt-4 pt-4 border-t border-slate-800">
                <div className="text-slate-500 text-xs mb-1">Reasons</div>
                <ul className="list-disc list-inside text-sm text-red-300 space-y-0.5">
                  {result.reasons.map((r, i) => (
                    <li key={i}>{r}</li>
                  ))}
                </ul>
              </div>
            )}
            <div className="mt-4 pt-4 border-t border-slate-800 flex gap-3">
              <button onClick={shareReport} className="text-xs bg-slate-800 hover:bg-slate-700 rounded-lg px-3 py-2">
                Share Verification Report (JSON)
              </button>
              <button onClick={printReport} className="text-xs bg-slate-800 hover:bg-slate-700 rounded-lg px-3 py-2">
                Print / Save as PDF
              </button>
              <span className="text-[11px] text-slate-600 self-center">Verification ID: {result.verification_id}</span>
            </div>
          </div>

          {rec && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
                <h3 className="text-xs uppercase tracking-wide text-slate-400 mb-3">Certificate Details</h3>
                <dl className="grid grid-cols-2 gap-y-2 text-xs">
                  <dt className="text-slate-500">Generator</dt>
                  <dd>{rec.plant_name || rec.generator_id}</dd>
                  <dt className="text-slate-500">Generator ID</dt>
                  <dd className="font-mono">{rec.generator_id}</dd>
                  <dt className="text-slate-500">Plant Location</dt>
                  <dd>{rec.plant_location || "—"}</dd>
                  <dt className="text-slate-500">Energy Source</dt>
                  <dd>{rec.energy_source || "—"}</dd>
                  <dt className="text-slate-500">Plant Capacity</dt>
                  <dd>{rec.plant_capacity_mw} MW</dd>
                  <dt className="text-slate-500">Energy Generated</dt>
                  <dd>{rec.energy_generated_mwh} MWh</dd>
                  <dt className="text-slate-500">REC Quantity</dt>
                  <dd>{rec.rec_quantity}</dd>
                  <dt className="text-slate-500">Generation Time</dt>
                  <dd>{fmtTime(rec.generation_timestamp)}</dd>
                  <dt className="text-slate-500">Issuance Time</dt>
                  <dd>{fmtTime(rec.issuance_timestamp)}</dd>
                  <dt className="text-slate-500">Original Owner</dt>
                  <dd className="font-mono truncate">{rec.original_owner}</dd>
                  <dt className="text-slate-500">Current Owner</dt>
                  <dd className="font-mono truncate">{rec.current_owner}</dd>
                  <dt className="text-slate-500">Status</dt>
                  <dd>{rec.status}</dd>
                  <dt className="text-slate-500">Retired</dt>
                  <dd>{rec.retired ? "Yes" : "No"}</dd>
                </dl>
              </div>

              <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
                <h3 className="text-xs uppercase tracking-wide text-slate-400 mb-3">Hash Comparison</h3>
                <dl className="space-y-2 text-xs mb-4">
                  <div>
                    <dt className="text-slate-500">Original hash (anchored at issuance)</dt>
                    <dd className="font-mono" title={result.original_hash}>{fmtHash(result.original_hash)}</dd>
                  </div>
                  <div>
                    <dt className="text-slate-500">Locally recalculated hash (right now)</dt>
                    <dd className="font-mono" title={result.recomputed_hash}>{fmtHash(result.recomputed_hash)}</dd>
                  </div>
                  <div>
                    <dt className="text-slate-500">On-chain hash</dt>
                    <dd className="font-mono" title={result.onchain_hash}>{fmtHash(result.onchain_hash)}</dd>
                  </div>
                </dl>
                <div className="text-xs text-slate-500 mb-1">Blockchain Transaction Hash</div>
                <div className="font-mono text-xs truncate mb-4" title={rec.blockchain_tx_hash}>{rec.blockchain_tx_hash || "pending sync"}</div>
                <div className="grid grid-cols-3 gap-2 text-center text-xs">
                  <div className="bg-slate-950 rounded-lg p-2">
                    <div className="text-slate-100 font-semibold">{result.ml_risk_score}</div>
                    ML Risk
                  </div>
                  <div className="bg-slate-950 rounded-lg p-2">
                    <div className="text-slate-100 font-semibold">{result.graph_risk_score}</div>
                    Graph Risk
                  </div>
                  <div className="bg-slate-950 rounded-lg p-2">
                    <div className="text-slate-100 font-semibold">{result.final_risk_score}</div>
                    Final Risk
                  </div>
                </div>
              </div>
            </div>
          )}

          {rec?.lifecycle?.length > 0 && (
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
              <h3 className="text-xs uppercase tracking-wide text-slate-400 mb-3">Transfer History</h3>
              <table className="w-full text-xs">
                <thead className="text-slate-500 uppercase text-[10px]">
                  <tr className="border-b border-slate-800">
                    <th className="text-left py-2">Type</th>
                    <th className="text-left py-2">From</th>
                    <th className="text-left py-2">To</th>
                    <th className="text-left py-2">Qty</th>
                    <th className="text-left py-2">Time</th>
                    <th className="text-left py-2">Blockchain</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800">
                  {rec.lifecycle.map((t) => (
                    <tr key={t.transaction_id}>
                      <td className="py-2">{t.transaction_type}</td>
                      <td className="py-2 font-mono truncate max-w-[120px]">{t.sender || "—"}</td>
                      <td className="py-2 font-mono truncate max-w-[120px]">{t.receiver || "—"}</td>
                      <td className="py-2">{t.quantity}</td>
                      <td className="py-2 text-slate-500">{fmtTime(t.transaction_timestamp)}</td>
                      <td className="py-2">
                        <BlockchainStatusBadge status={t.blockchain_status} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {auditLog.length > 0 && (
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
              <h3 className="text-xs uppercase tracking-wide text-slate-400 mb-3">Audit Trail (hash-chained)</h3>
              <div className="space-y-2">
                {auditLog.map((a) => (
                  <div key={a.id} className="text-xs border-l-2 border-slate-800 pl-3 py-1">
                    <span
                      className={`font-semibold ${
                        a.event_type.includes("TAMPER") || a.event_type === "HASH_MISMATCH"
                          ? "text-red-400"
                          : "text-slate-300"
                      }`}
                    >
                      {a.event_type}
                    </span>{" "}
                    <span className="text-slate-500">by {a.changed_by} via {a.source}</span>{" "}
                    <span className="text-slate-600">-- {fmtTime(a.changed_at)}</span>
                    {a.new_value && (
                      <div className="text-slate-500 mt-0.5 truncate">{JSON.stringify(a.new_value)}</div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {history.length > 0 && (
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
              <h3 className="text-xs uppercase tracking-wide text-slate-400 mb-3">Verification History for This REC</h3>
              <table className="w-full text-xs">
                <thead className="text-slate-500 uppercase text-[10px]">
                  <tr className="border-b border-slate-800">
                    <th className="text-left py-2">Verification ID</th>
                    <th className="text-left py-2">Company</th>
                    <th className="text-left py-2">Result</th>
                    <th className="text-left py-2">Blockchain</th>
                    <th className="text-left py-2">Time</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800">
                  {history.map((h) => (
                    <tr key={h.verification_id}>
                      <td className="py-2 font-mono">{h.verification_id}</td>
                      <td className="py-2">{h.verifier_company || "—"}</td>
                      <td className="py-2">
                        <VerificationStatusBadge result={h.result} />
                      </td>
                      <td className="py-2">
                        <BlockchainStatusBadge status={h.blockchain_status} />
                      </td>
                      <td className="py-2 text-slate-500">{fmtTime(h.requested_at)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
